const childGrowthData = [
    {
        "week":1,
        "fetusSizeMM": 1,
        "fetusSizeInches": 0.04,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Poppy seed",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "free": false
    },
    {
        "week": 2,
        "fetusSizeMM": 1,
        "fetusSizeInches": 0.04,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Poppy seed",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "free": false
    },
    {
        "week": 3,
        "fetusSizeMM": 1,
        "fetusSizeInches": 0.04,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Poppy seed",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "free": false
    },
    {
        "week": 4,
        "fetusSizeMM": 1,
        "fetusSizeInches": 0.04,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Poppy seed",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/1.png",
        "free": false
    },
    {
        "week": 5,
        "fetusSizeMM": 2,
        "fetusSizeInches": 0.08,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Sesame seed",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/2.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/2.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/2.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/2.png",
        "free": false
    },
    {
        "week": 6,
        "fetusSizeMM": 6,
        "fetusSizeInches": 0.2,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Pea",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/3.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/3.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/3.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/3.png",
        "free": null
    },
    {
        "week": 7,
        "fetusSizeMM": 10,
        "fetusSizeInches": 0.4,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Raspberry",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/4.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/4.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/4.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/4.png",
        "free": null
    },
    {
        "week": 8,
        "fetusSizeMM": 16,
        "fetusSizeInches": 0.6,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Grape",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/5.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/5.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/5.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/5.png",
        "free": null
    },
    {
        "week": 9,
        "fetusSizeMM": 22,
        "fetusSizeInches": 0.9,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Strawberry",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/6.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/6.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/6.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/6.png",
        "free": null
    },
    {
        "week": 10,
        "fetusSizeMM": 30,
        "fetusSizeInches": 1.2,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Small apricot",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/7.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/7.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/7.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/7.png",
        "free": null
    },
    {
        "week": 11,
        "fetusSizeMM": 41,
        "fetusSizeInches": 1.6,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Fig",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/8.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/8.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/8.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/8.png",
        "free": null
    },
    {
        "week": 12,
        "fetusSizeMM": 54,
        "fetusSizeInches": 2.1,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Plum",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/9.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/9.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/9.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/9.png",
        "free": null
    },
    {
        "week": 13,
        "fetusSizeMM": 74,
        "fetusSizeInches": 2.9,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Peach",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/10.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/10.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/10.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/10.png",
        "free": null
    },
    {
        "week": 14,
        "fetusSizeMM": 87,
        "fetusSizeInches": 3.4,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Lemon",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/11.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/11.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/11.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/11.png",
        "free": null
    },
    {
        "week": 15,
        "fetusSizeMM": 100,
        "fetusSizeInches": 3.9,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Apple",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/12.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/12.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/12.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/12.png",
        "free": null
    },
    {
        "week": 16,
        "fetusSizeMM": 116,
        "fetusSizeInches": 4.5,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Avocado",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/13.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/13.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/13.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/13.png",
        "free": null
    },
    {
        "week": 17,
        "fetusSizeMM": 130,
        "fetusSizeInches": 5.1,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Turnip",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/14.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/14.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/14.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/14.png",
        "free": null
    },
    {
        "week": 18,
        "fetusSizeMM": 145,
        "fetusSizeInches": 5.7,
        "fetusWeightG": 200,
        "fetusWeightOz": 7,
        "babySizeFruitComparison": "Potato",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/15.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/15.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/15.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/15.png",
        "free": null
    },
    {
        "week": 19,
        "fetusSizeMM": 155,
        "fetusSizeInches": 6.1,
        "fetusWeightG": 240,
        "fetusWeightOz": 8.4,
        "babySizeFruitComparison": "Mango",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/16.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/16.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/16.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/16.png",
        "free": null
    },
    {
        "week": 20,
        "fetusSizeMM": 250,
        "fetusSizeInches": 9.8,
        "fetusWeightG": 312,
        "fetusWeightOz": 11,
        "babySizeFruitComparison": "Banana",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/17.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/17.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/17.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/17.png",
        "free": null
    },
    {
        "week": 21,
        "fetusSizeMM": 267,
        "fetusSizeInches": 10.5,
        "fetusWeightG": 350,
        "fetusWeightOz": 12.3,
        "babySizeFruitComparison": "Carrot",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/18.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/18.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/18.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/18.png",
        "free": null
    },
    {
        "week": 22,
        "fetusSizeMM": 270,
        "fetusSizeInches": 10.6,
        "fetusWeightG": 430,
        "fetusWeightOz": 15,
        "babySizeFruitComparison": "Papaya",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/19.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/19.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/19.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/19.png",
        "free": null
    },
    {
        "week": 23,
        "fetusSizeMM": 280,
        "fetusSizeInches": 11,
        "fetusWeightG": 500,
        "fetusWeightOz": 1.1,
        "babySizeFruitComparison": "Grapefruit",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/20.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/20.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/20.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/20.png",
        "free": null
    },
    {
        "week": 24,
        "fetusSizeMM": 300,
        "fetusSizeInches": 12,
        "fetusWeightG": 600,
        "fetusWeightOz": 1.3,
        "babySizeFruitComparison": "Corn on the cob",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/21.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/21.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/21.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/21.png",
        "free": null
    },
    {
        "week": 25,
        "fetusSizeMM": 340,
        "fetusSizeInches": 13,
        "fetusWeightG": 700,
        "fetusWeightOz": 1.5,
        "babySizeFruitComparison": "Courgette",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/22.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/22.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/22.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/22.png",
        "free": null
    },
    {
        "week": 26,
        "fetusSizeMM": 355,
        "fetusSizeInches": 14,
        "fetusWeightG": 760,
        "fetusWeightOz": 1.7,
        "babySizeFruitComparison": "Cucumber",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/23.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/23.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/23.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/23.png",
        "free": null
    },
    {
        "week": 27,
        "fetusSizeMM": 360,
        "fetusSizeInches": 14.1,
        "fetusWeightG": 900,
        "fetusWeightOz": 2,
        "babySizeFruitComparison": "Cauliflower",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/24.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/24.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/24.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/24.png",
        "free": null
    },
    {
        "week": 28,
        "fetusSizeMM": 370,
        "fetusSizeInches": 14.5,
        "fetusWeightG": 1000,
        "fetusWeightOz": 2.2,
        "babySizeFruitComparison": "Aubergine",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/25.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/25.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/25.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/25.png",
        "free": null
    },
    {
        "week": 29,
        "fetusSizeMM": 386,
        "fetusSizeInches": 15.1,
        "fetusWeightG": 1300,
        "fetusWeightOz": 2.9,
        "babySizeFruitComparison": "Squash",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/26.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/26.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/26.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/26.png",
        "free": null
    },
    {
        "week": 30,
        "fetusSizeMM": 399,
        "fetusSizeInches": 15.7,
        "fetusWeightG": 1500,
        "fetusWeightOz": 3.3,
        "babySizeFruitComparison": "Cabbage",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/27.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/27.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/27.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/27.png",
        "free": null
    },
    {
        "week": 31,
        "fetusSizeMM": 415,
        "fetusSizeInches": 16.3,
        "fetusWeightG": 1600,
        "fetusWeightOz": 3.5,
        "babySizeFruitComparison": "Coconut",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/28.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/28.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/28.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/28.png",
        "free": null
    },
    {
        "week": 32,
        "fetusSizeMM": 425,
        "fetusSizeInches": 16.7,
        "fetusWeightG": 1700,
        "fetusWeightOz": 3.7,
        "babySizeFruitComparison": "Butternut squash",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/29.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/29.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/29.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/29.png",
        "free": null
    },
    {
        "week": 33,
        "fetusSizeMM": 430,
        "fetusSizeInches": 17,
        "fetusWeightG": 1900,
        "fetusWeightOz": 4.25,
        "babySizeFruitComparison": "Pineapple",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/30.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/30.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/30.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/30.png",
        "free": null
    },
    {
        "week": 34,
        "fetus_size_mm_cm": "45cm",
        "fetus_size_inches": "17.7 inches",
        "fetus_weight_g_kg": "2.1kg",
        "fetus_weight_oz_lbs": "4.5lbs",
        "baby_size_fruit_comparison": "Cantaloupe melon",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/31.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/31.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/31.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/31.png",
        "free": null
    },
    {
        "week": 35,
        "fetus_size_mm_cm": "47cm",
        "fetus_size_inches": "18.5 inches",
        "fetus_weight_g_kg": "2.5kg",
        "fetus_weight_oz_lbs": "5.5lbs",
        "baby_size_fruit_comparison": "Honeydew melon",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/32.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/32.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/32.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/32.png",
        "free": null
    },
    {
        "week": 36,
        "fetus_size_mm_cm": "47.4cm",
        "fetus_size_inches": "18.6 inches",
        "fetus_weight_g_kg": "2.7kg",
        "fetus_weight_oz_lbs": "5.9lbs",
        "baby_size_fruit_comparison": "Romaine lettuce",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/33.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/33.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/33.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/33.png",
        "free": null
    },
    {
        "week": 37,
        "fetus_size_mm_cm": "48.6cm",
        "fetus_size_inches": "19.1 inches",
        "fetus_weight_g_kg": "2.8kg",
        "fetus_weight_oz_lbs": "6.1lbs",
        "baby_size_fruit_comparison": "Leek",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/34.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/34.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/34.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/34.png",
        "free": null
    },
    {
        "week": 38,
        "fetus_size_mm_cm": "49.8cm",
        "fetus_size_inches": "19.6 inches",
        "fetus_weight_g_kg": "2.9kg",
        "fetus_weight_oz_lbs": "6.5lbs",
        "baby_size_fruit_comparison": "Rhubarb",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/35.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/35.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/35.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/35.png",
        "free": null
    },
    {
        "week": 39,
        "fetus_size_mm_cm": "50.1cm",
        "fetus_size_inches": "19.7 inches",
        "fetus_weight_g_kg": "3.1kg",
        "fetus_weight_oz_lbs": "7lbs",
        "baby_size_fruit_comparison": "Small watermelon",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/36.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/36.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/36.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/36.png",
        "free": null
    },
    {
        "week": 40,
        "fetus_size_mm_cm": "50.8cm",
        "fetus_size_inches": "20 inches",
        "fetus_weight_g_kg": "3.4kg",
        "fetus_weight_oz_lbs": "7.5lbs",
        "baby_size_fruit_comparison": "Small pumpkin",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/37.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/37.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/37.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/37.png",
        "free": null
    },
    {
        "week": 41,
        "fetus_size_mm_cm": "52cm",
        "fetus_size_inches": "20.5 inches",
        "fetus_weight_g_kg": "3.8kg",
        "fetus_weight_oz_lbs": "8.5lbs",
        "baby_size_fruit_comparison": "Watermelon",
        "image1": "https://midwife-backend-rouge.vercel.app/fruits/38.png",
        "image2": "https://midwife-backend-rouge.vercel.app/fruits/38.png",
        "image1Link": "https://midwife-backend-rouge.vercel.app/fruits/38.png",
        "image2Link": "https://midwife-backend-rouge.vercel.app/fruits/38.png",
        "free": null
    }
]

module.exports=childGrowthData