const childGrowthData = [
    {
        "week": 4,
        "fetusSizeMM": 1,
        "fetusSizeInches": 0.04,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Poppy seed",
        "image1": "https://www.alamy.com/aggregator-api/download?url=https%3A%2F%2Fc8.alamy.com%2Fcomp%2FM6YGKJ%2Fpoppy-seed-size-about-1mm-isolated-on-white-background-light-micrograph-M6YGKJ.jpg",
        "image2": "https://media.istockphoto.com/id/1455051200/photo/poppy-seeds.jpg?s=612x612&w=0&k=20&c=UtVQj4DqaH_Gm-7xNQtz8EDETvNNTl_P29qg0uJw-NI=",
        "image1Link": "https://www.alamy.com/aggregator-api/download?url=https%3A%2F%2Fc8.alamy.com%2Fcomp%2FM6YGKJ%2Fpoppy-seed-size-about-1mm-isolated-on-white-background-light-micrograph-M6YGKJ.jpg",
        "image2Link": "https://media.istockphoto.com/id/1455051200/photo/poppy-seeds.jpg?s=612x612&w=0&k=20&c=UtVQj4DqaH_Gm-7xNQtz8EDETvNNTl_P29qg0uJw-NI=",
        "free": false
    },
    {
        "week": 5,
        "fetusSizeMM": 2,
        "fetusSizeInches": 0.08,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Sesame seed",
        "image1": "https://www.flickr.com/photos/rinaldotromp/7188531448/in/photostream/",
        "image2": null,
        "image1Link": "https://www.flickr.com/photos/rinaldotromp/7188531448/in/photostream/",
        "image2Link": null,
        "free": false
    },
    {
        "week": 6,
        "fetusSizeMM": 6,
        "fetusSizeInches": 0.2,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Pea",
        "image1": "https://www.pexels.com/photo/green-leaf-on-black-background-8067747/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/green-leaf-on-black-background-8067747/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 7,
        "fetusSizeMM": 10,
        "fetusSizeInches": 0.4,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Raspberry",
        "image1": "https://www.pexels.com/photo/close-up-photography-of-red-berry-fruit-1685581/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/close-up-photography-of-red-berry-fruit-1685581/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 8,
        "fetusSizeMM": 16,
        "fetusSizeInches": 0.6,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Grape",
        "image1": "https://www.pexels.com/photo/red-grapes-23042/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/red-grapes-23042/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 9,
        "fetusSizeMM": 22,
        "fetusSizeInches": 0.9,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Strawberry",
        "image1": "https://www.pexels.com/photo/strawberry-fruit-on-brown-wooden-surface-934055/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/strawberry-fruit-on-brown-wooden-surface-934055/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 10,
        "fetusSizeMM": 30,
        "fetusSizeInches": 1.2,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Small apricot",
        "image1": "https://www.freepik.com/free-photo/yellow-peaches-isolated-white_9829868.htm#fromView=search&page=1&position=4&uuid=2568ec77-abe1-4320-b5d3-eb8651c86177&query=Apricot+Fruit",
        "image2": "https://www.freepik.com/free-psd/view-ripe-sweet-fruit_37298554.htm#fromView=search&page=1&position=24&uuid=2568ec77-abe1-4320-b5d3-eb8651c86177&query=Apricot+Fruit",
        "image1Link": "https://www.freepik.com/free-photo/yellow-peaches-isolated-white_9829868.htm#fromView=search&page=1&position=4&uuid=2568ec77-abe1-4320-b5d3-eb8651c86177&query=Apricot+Fruit",
        "image2Link": "https://www.freepik.com/free-psd/view-ripe-sweet-fruit_37298554.htm#fromView=search&page=1&position=24&uuid=2568ec77-abe1-4320-b5d3-eb8651c86177&query=Apricot+Fruit",
        "free": null
    },
    {
        "week": 11,
        "fetusSizeMM": 41,
        "fetusSizeInches": 1.6,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Fig",
        "image1": "https://www.pexels.com/photo/fig-fruit-on-white-background-5419213/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/fig-fruit-on-white-background-5419213/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 12,
        "fetusSizeMM": 54,
        "fetusSizeInches": 2.1,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Plum",
        "image1": "https://www.pexels.com/photo/a-piece-of-red-plum-on-a-white-surface-4828492/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/a-piece-of-red-plum-on-a-white-surface-4828492/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 13,
        "fetusSizeMM": 74,
        "fetusSizeInches": 2.9,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Peach",
        "image1": "https://unsplash.com/photos/ripe-peach-fruit-rqABly7c9j0",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/ripe-peach-fruit-rqABly7c9j0",
        "image2Link": null,
        "free": null
    },
    {
        "week": 14,
        "fetusSizeMM": 87,
        "fetusSizeInches": 3.4,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Lemon",
        "image1": "https://unsplash.com/photos/closeup-photo-of-yellow-lemon-s05XKB6jK2c",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/closeup-photo-of-yellow-lemon-s05XKB6jK2c",
        "image2Link": null,
        "free": null
    },
    {
        "week": 15,
        "fetusSizeMM": 100,
        "fetusSizeInches": 3.9,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Apple",
        "image1": "https://unsplash.com/photos/red-apple-fruit-gDPaDDy6_WE",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/red-apple-fruit-gDPaDDy6_WE",
        "image2Link": null,
        "free": null
    },
    {
        "week": 16,
        "fetusSizeMM": 116,
        "fetusSizeInches": 4.5,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Avocado",
        "image1": "https://unsplash.com/photos/sliced-avocado-EMX1eJ1BcgU",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/sliced-avocado-EMX1eJ1BcgU",
        "image2Link": null,
        "free": null
    },
    {
        "week": 17,
        "fetusSizeMM": 130,
        "fetusSizeInches": 5.1,
        "fetusWeightG": null,
        "fetusWeightOz": null,
        "babySizeFruitComparison": "Turnip",
        "image1": "https://www.freepik.com/premium-ai-image/natural-fresh-turnip-png-style-white-background_354445630.htm",
        "image2": null,
        "image1Link": "https://www.freepik.com/premium-ai-image/natural-fresh-turnip-png-style-white-background_354445630.htm",
        "image2Link": null,
        "free": null
    },
    {
        "week": 18,
        "fetusSizeMM": 145,
        "fetusSizeInches": 5.7,
        "fetusWeightG": 200,
        "fetusWeightOz": 7,
        "babySizeFruitComparison": "Potato",
        "image1": "https://www.pexels.com/photo/close-up-photo-of-a-potato-on-a-green-surface-11633653/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/close-up-photo-of-a-potato-on-a-green-surface-11633653/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 19,
        "fetusSizeMM": 155,
        "fetusSizeInches": 6.1,
        "fetusWeightG": 240,
        "fetusWeightOz": 8.4,
        "babySizeFruitComparison": "Mango",
        "image1": "https://www.pexels.com/photo/fruit-on-white-ceramic-plate-8756771/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/fruit-on-white-ceramic-plate-8756771/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 20,
        "fetusSizeMM": 250,
        "fetusSizeInches": 9.8,
        "fetusWeightG": 312,
        "fetusWeightOz": 11,
        "babySizeFruitComparison": "Banana",
        "image1": "https://www.pexels.com/photo/fresh-banana-with-spots-on-yellow-peel-7194974/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/fresh-banana-with-spots-on-yellow-peel-7194974/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 21,
        "fetusSizeMM": 267,
        "fetusSizeInches": 10.5,
        "fetusWeightG": 350,
        "fetusWeightOz": 12.3,
        "babySizeFruitComparison": "Carrot",
        "image1": "https://www.pexels.com/photo/top-view-of-a-carrot-on-an-orange-surface-5621248/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/top-view-of-a-carrot-on-an-orange-surface-5621248/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 22,
        "fetusSizeMM": 270,
        "fetusSizeInches": 10.6,
        "fetusWeightG": 430,
        "fetusWeightOz": 15,
        "babySizeFruitComparison": "Papaya",
        "image1": "https://www.pexels.com/photo/sliced-apple-fruit-on-white-table-7656860/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/sliced-apple-fruit-on-white-table-7656860/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 23,
        "fetusSizeMM": 280,
        "fetusSizeInches": 11,
        "fetusWeightG": 500,
        "fetusWeightOz": 1.1,
        "babySizeFruitComparison": "Grapefruit",
        "image1": "https://www.pexels.com/photo/a-person-s-hand-holding-agrapefruit-6404981/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/a-person-s-hand-holding-agrapefruit-6404981/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 24,
        "fetusSizeMM": 300,
        "fetusSizeInches": 12,
        "fetusWeightG": 600,
        "fetusWeightOz": 1.3,
        "babySizeFruitComparison": "Corn on the cob",
        "image1": "https://www.pexels.com/photo/corns-on-blue-surface-5678107/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/corns-on-blue-surface-5678107/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 25,
        "fetusSizeMM": 340,
        "fetusSizeInches": 13,
        "fetusWeightG": 700,
        "fetusWeightOz": 1.5,
        "babySizeFruitComparison": "Courgette",
        "image1": "https://www.pexels.com/photo/green-vegetable-on-brown-wooden-table-11643027/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/green-vegetable-on-brown-wooden-table-11643027/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 26,
        "fetusSizeMM": 355,
        "fetusSizeInches": 14,
        "fetusWeightG": 760,
        "fetusWeightOz": 1.7,
        "babySizeFruitComparison": "Cucumber",
        "image1": "https://unsplash.com/photos/green-cucumber-on-white-surface-UrLT3x0x9sA",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/green-cucumber-on-white-surface-UrLT3x0x9sA",
        "image2Link": null,
        "free": null
    },
    {
        "week": 27,
        "fetusSizeMM": 360,
        "fetusSizeInches": 14.1,
        "fetusWeightG": 900,
        "fetusWeightOz": 2,
        "babySizeFruitComparison": "Cauliflower",
        "image1": "https://unsplash.com/photos/a-head-of-broccoli-growing-in-a-garden-1g9kfYSnnus",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/a-head-of-broccoli-growing-in-a-garden-1g9kfYSnnus",
        "image2Link": null,
        "free": null
    },
    {
        "week": 28,
        "fetusSizeMM": 370,
        "fetusSizeInches": 14.5,
        "fetusWeightG": 1000,
        "fetusWeightOz": 2.2,
        "babySizeFruitComparison": "Aubergine",
        "image1": "https://www.pexels.com/photo/purple-eggplant-3948546/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/purple-eggplant-3948546/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 29,
        "fetusSizeMM": 386,
        "fetusSizeInches": 15.1,
        "fetusWeightG": 1300,
        "fetusWeightOz": 2.9,
        "babySizeFruitComparison": "Squash",
        "image1": "https://unsplash.com/photos/brown-potato-on-white-table-zdpl5Nzvjsw",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/brown-potato-on-white-table-zdpl5Nzvjsw",
        "image2Link": null,
        "free": null
    },
    {
        "week": 30,
        "fetusSizeMM": 399,
        "fetusSizeInches": 15.7,
        "fetusWeightG": 1500,
        "fetusWeightOz": 3.3,
        "babySizeFruitComparison": "Cabbage",
        "image1": "https://unsplash.com/photos/green-leaf-vegetable-on-white-surface-7iRMOXXxH7c",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/green-leaf-vegetable-on-white-surface-7iRMOXXxH7c",
        "image2Link": null,
        "free": null
    },
    {
        "week": 31,
        "fetusSizeMM": 415,
        "fetusSizeInches": 16.3,
        "fetusWeightG": 1600,
        "fetusWeightOz": 3.5,
        "babySizeFruitComparison": "Coconut",
        "image1": "https://unsplash.com/photos/brown-coconut-fruit-on-blue-background-tL3D1a649u0",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/brown-coconut-fruit-on-blue-background-tL3D1a649u0",
        "image2Link": null,
        "free": null
    },
    {
        "week": 32,
        "fetusSizeMM": 425,
        "fetusSizeInches": 16.7,
        "fetusWeightG": 1700,
        "fetusWeightOz": 3.7,
        "babySizeFruitComparison": "Butternut squash",
        "image1": "https://unsplash.com/photos/brown-potato-on-white-table-zdpl5Nzvjsw",
        "image2": null,
        "image1Link": "https://unsplash.com/photos/brown-potato-on-white-table-zdpl5Nzvjsw",
        "image2Link": null,
        "free": null
    },
    {
        "week": 33,
        "fetusSizeMM": 430,
        "fetusSizeInches": 17,
        "fetusWeightG": 1900,
        "fetusWeightOz": 4.25,
        "babySizeFruitComparison": "Pineapple",
        "image1": "https://www.pexels.com/photo/pineapple-947879/",
        "image2": null,
        "image1Link": "https://www.pexels.com/photo/pineapple-947879/",
        "image2Link": null,
        "free": null
    },
    {
        "week": 34,
        "fetus_size_mm_cm": "45cm",
        "fetus_size_inches": "17.7 inches",
        "fetus_weight_g_kg": "2.1kg",
        "fetus_weight_oz_lbs": "4.5lbs",
        "baby_size_fruit_comparison": "Cantaloupe melon",
        "image_1": "https://www.pexels.com/photo/melon-and-sliced-kiwis-on-green-surface-7227393/",
        "image_2": "",
        "free": null
    },
    {
        "week": 35,
        "fetus_size_mm_cm": "47cm",
        "fetus_size_inches": "18.5 inches",
        "fetus_weight_g_kg": "2.5kg",
        "fetus_weight_oz_lbs": "5.5lbs",
        "baby_size_fruit_comparison": "Honeydew melon",
        "image_1": "https://www.pexels.com/photo/person-holding-sliced-fruit-4772942/",
        "image_2": "",
        "free": null
    },
    {
        "week": 36,
        "fetus_size_mm_cm": "47.4cm",
        "fetus_size_inches": "18.6 inches",
        "fetus_weight_g_kg": "2.7kg",
        "fetus_weight_oz_lbs": "5.9lbs",
        "baby_size_fruit_comparison": "Romaine lettuce",
        "image_1": "https://www.pexels.com/photo/romaine-lettuce-on-a-flat-surface-5202194/",
        "image_2": "",
        "free": null
    },
    {
        "week": 37,
        "fetus_size_mm_cm": "48.6cm",
        "fetus_size_inches": "19.1 inches",
        "fetus_weight_g_kg": "2.8kg",
        "fetus_weight_oz_lbs": "6.1lbs",
        "baby_size_fruit_comparison": "Leek",
        "image_1": "https://unsplash.com/photos/green-spring-onions-CQOm4U4E71M",
        "image_2": "",
        "free": null
    },
    {
        "week": 38,
        "fetus_size_mm_cm": "49.8cm",
        "fetus_size_inches": "19.6 inches",
        "fetus_weight_g_kg": "2.9kg",
        "fetus_weight_oz_lbs": "6.5lbs",
        "baby_size_fruit_comparison": "Rhubarb",
        "image_1": "https://unsplash.com/photos/red-and-white-chili-on-white-textile-8ULwUsmbA-E",
        "image_2": "",
        "free": null
    },
    {
        "week": 39,
        "fetus_size_mm_cm": "50.1cm",
        "fetus_size_inches": "19.7 inches",
        "fetus_weight_g_kg": "3.1kg",
        "fetus_weight_oz_lbs": "7lbs",
        "baby_size_fruit_comparison": "Small watermelon",
        "image_1": "https://www.pexels.com/photo/gardener-s-gloved-hand-holding-ripe-watermelon-29799547/",
        "image_2": "",
        "free": null
    },
    {
        "week": 40,
        "fetus_size_mm_cm": "50.8cm",
        "fetus_size_inches": "20 inches",
        "fetus_weight_g_kg": "3.4kg",
        "fetus_weight_oz_lbs": "7.5lbs",
        "baby_size_fruit_comparison": "Small pumpkin",
        "image_1": "https://www.pexels.com/photo/a-person-holding-a-pumpkin-10821242/",
        "image_2": "",
        "free": null
    },
    {
        "week": 41,
        "fetus_size_mm_cm": "52cm",
        "fetus_size_inches": "20.5 inches",
        "fetus_weight_g_kg": "3.8kg",
        "fetus_weight_oz_lbs": "8.5lbs",
        "baby_size_fruit_comparison": "Watermelon",
        "image_1": "https://www.freepik.com/premium-photo/big-ripe-watermelon-isolated-white_4135963.htm#fromView=search&page=1&position=7&uuid=e721a2d0-4b60-4ed1-8b69-64856728126a&query=watermelon",
        "image_2": "",
        "free": null
    }
]

module.exports=childGrowthData